parameters:
#    control_f_preuba.example.class: ControlF\PreubaBundle\Example

services:
#    control_f_preuba.example:
#        class: %control_f_preuba.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
